config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'blogs#index', as: 'home'
  
  get 'about' => 'pages#about', as: 'about'
  
  resources :blogs
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, presence: true,
                        length: {minimum: 5}
                        
                        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  
  def index
    @blogs = Blog.all
  end
  
  def show
    @blog = Blog.find(params[:id])
  end
  
  def new
    @blog = Blog.new
  end
  
  def create
    #render plain: params[:blog].inspect
    @blog = Blog.new(blog_params) 
    
    if (@blog.save)
      redirect_to @blog
    else
      render 'new'
    end
  end
  
  def edit
    @blog = Blog.find(params[:id])
  end
  
  def update
    @blog = Blog.find(params[:id])
    
    if (@blog.update(blog_params))
      redirect_to @blog
    else
      render 'edit'
    end
    
    def destroy
      @blog = Blog.find(params[:id])
      @blog.destroy
      
      redirect_to blogs_path
    end
  
    
  end
  
  private def blog_params
    params.require(:blog).permit(:title, :text)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def about
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogs/edit.html.erb
<h1>Edit Post</h1>


<%= form_for :blog, url: blog_path(@blog), method: :patch do |f| %>
    <% if @blog.errors.any? %>
        <% @blog.errors.full_messages.each do |msg| %>
            <div class = "alert alert-danger"><%= msg %></div> 
        <% end %>
    <% end %>
    
<p>
    <%= f.label :title %> <br>
    <%= f.text_field(:title, {:class => 'form_control'}) %>
</p>

<p>
    <%= f.label :text %> <br>
    <%= f.text_area(:text, {:class => 'form_control'}) %>
</p>

<p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
</p>

<% end %>

app/views/blogs/index.html.erb
<h1>Blog Posts</h1>

<% @blogs.each do |blog| %>
    <div class = 'well'>
        <h3><%= blog.title %></h3>
        <p><%= blog.text %></p>
        <%= link_to "Read more", blog_path(blog), :class => 'btn btn-default' %>
    </div>    
<% end %>

app/views/blogs/new.html.erb
<h1>Add Post</h1>


<%= form_for :blog, url: blogs_path do |f| %>
    <% if @blog.errors.any? %>
        <% @blog.errors.full_messages.each do |msg| %>
            <div class = "alert alert-danger"><%= msg %></div> 
        <% end %>
    <% end %>
    
<p>
    <%= f.label :title %> <br>
    <%= f.text_field(:title, {:class => 'form_control'}) %>
</p>

<p>
    <%= f.label :text %> <br>
    <%= f.text_area(:text, {:class => 'form_control'}) %>
</p>

<p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
</p>

<% end %>

app/views/blogs/show.html.erb
<h2><%= @blog.title %></h2>
<p><%= @blog.text %></p>

<hr>
<%= link_to 'Edit', edit_blog_path(@blog), :class => 'btn btn-default' %>
<%= link_to 'Delete', blog_path(@blog), 
                                  method: :delete,
                                  data: {Confirm: 'Are you sure?'},
                                  :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Murblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <nav class="navbar navbar-default">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">MurBlog</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to "Home", home_path %></li> 
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Create Blog", new_blog_path %></li> 
            </ul>
          </div><!--/.nav-collapse -->
        </div>  
    </nav>
<div class='container'>    
    <%= yield %>
</div>
  </body>
</html>

app/views/pages/pages.html.erb
<h1>This is the adout page</h1>